name: CI/CD Pipeline
run-name: Pipeline launched by ${{ github.actor }}


on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: devops-exam-2024
        slot-name: <Name-of-Deployment-Slot>
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
